version: "3.9"

services:
  db:
    image: postgres:13.5
    container_name: mikbooks_db
    restart: unless-stopped
    ports:
      - 5432:5432
    env_file:
      - .env.production.local
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - mikbooks_network

  web:
    restart: unless-stopped
    build:
      dockerfile: Dockerfile.prod
    env_file:
      - .env.production.local
    command:
       sh -c "
        npx prisma generate
        && npx prisma migrate dev
        && node dist/main.js
      "
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - mikbooks_network

volumes:
  postgres-data:

networks:
  mikbooks_network:
    driver: bridge